### ISSUE TITLE
Map?

### ISSUE THREAD

**Issue by xogeny** [patrimart/monadness-js#1]
Is there any particular reason you didn't include a `map` operation?  I could submit a PR for it (assuming that isn't any technical barrier).

**Comment by patrimart** [comment]
The library is young. While this lib's Either and Option were heavily influenced by Javaslang's implementations, I want to research how Scala and Haskell implement the feature.

**Comment by xogeny** [comment]
Well I haven't used Javaslang at all, but Scala's version would look like this in TypeScript:

```
   map((x: T) => R): Option<R>
```

**Comment by patrimart** [comment]
Mapping added in version 0.5.1.
