### ISSUE TITLE
Why the closures

### ISSUE THREAD

**Issue by xogeny** [patrimart/monadness-js#2]
Why does `getOrElse` take a closure?  Is it because you don't want the expression evaluated in the case where the `Option` has a value?  I can understand that use case, but I would think having a separate method to handle that case.  Otherwise, it seems unnecessarily complex.  I realize Scala uses its special "no argument closure" syntax (I don't know the formal name).  But it also includes the shorthand syntax of being able to provide an expression as an instance of such a closure.  But in TypeScript, as far as I can see, you are forced to say `() => x` (vs. just `x`) which is a bit awkward.  Or am I missing something?

**Comment by patrimart** [comment]
You're looking for the `getOrElseGet (right: R): R` method.

**Comment by xogeny** [comment]
Yep, you are right.  I missed that.  Sorry.
